global using Microsoft.EntityFrameworkCore;
global using Domain.Entities;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.AspNetCore.Identity;
global using Application.Interfaces.Infrastructure;
global using System.Linq.Expressions;
global using Domain.Repositories;
global using Domain.Constants;
global using Mapster;